# CMake generated Testfile for 
# Source directory: /home/linux/HPCOS-GC-RECOMP/ModernGekko
# Build directory: /home/linux/HPCOS-GC-RECOMP/ModernGekko/build-llvm20
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test("moderngekko.dol_patch" "/home/linux/HPCOS-GC-RECOMP/ModernGekko/build-llvm20/moderngekko_dol_patch_test")
set_tests_properties("moderngekko.dol_patch" PROPERTIES  _BACKTRACE_TRIPLES "/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;639;add_test;/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;0;")
add_test("moderngekko.frontend_config" "/home/linux/HPCOS-GC-RECOMP/ModernGekko/build-llvm20/moderngekko_frontend_config_test")
set_tests_properties("moderngekko.frontend_config" PROPERTIES  _BACKTRACE_TRIPLES "/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;647;add_test;/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;0;")
add_test("moderngekko.frontend_config_gamecube" "/home/linux/HPCOS-GC-RECOMP/ModernGekko/build-llvm20/moderngekko_frontend_config_gamecube_test")
set_tests_properties("moderngekko.frontend_config_gamecube" PROPERTIES  _BACKTRACE_TRIPLES "/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;657;add_test;/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;0;")
add_test("moderngekko.netplay_protocol" "/home/linux/HPCOS-GC-RECOMP/ModernGekko/build-llvm20/moderngekko_netplay_protocol_test")
set_tests_properties("moderngekko.netplay_protocol" PROPERTIES  _BACKTRACE_TRIPLES "/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;695;add_test;/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;0;")
add_test("moderngekko.game_inspect" "/home/linux/HPCOS-GC-RECOMP/ModernGekko/build-llvm20/moderngekko_game_inspect_test")
set_tests_properties("moderngekko.game_inspect" PROPERTIES  _BACKTRACE_TRIPLES "/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;700;add_test;/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;0;")
add_test("moderngekko.module_abi" "/home/linux/HPCOS-GC-RECOMP/ModernGekko/build-llvm20/moderngekko_module_abi_test")
set_tests_properties("moderngekko.module_abi" PROPERTIES  _BACKTRACE_TRIPLES "/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;708;add_test;/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;0;")
add_test("moderngekko.module_loader" "/home/linux/HPCOS-GC-RECOMP/ModernGekko/build-llvm20/moderngekko_module_loader_test")
set_tests_properties("moderngekko.module_loader" PROPERTIES  _BACKTRACE_TRIPLES "/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;739;add_test;/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;0;")
add_test("moderngekko.mod_loader" "/home/linux/HPCOS-GC-RECOMP/ModernGekko/build-llvm20/moderngekko_mod_loader_test")
set_tests_properties("moderngekko.mod_loader" PROPERTIES  _BACKTRACE_TRIPLES "/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;766;add_test;/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;0;")
add_test("moderngekko.cpu_primitives" "/home/linux/HPCOS-GC-RECOMP/ModernGekko/build-llvm20/moderngekko_cpu_primitives_test")
set_tests_properties("moderngekko.cpu_primitives" PROPERTIES  _BACKTRACE_TRIPLES "/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;778;add_test;/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;0;")
add_test("moderngekko.address_space" "/home/linux/HPCOS-GC-RECOMP/ModernGekko/build-llvm20/moderngekko_address_space_test")
set_tests_properties("moderngekko.address_space" PROPERTIES  _BACKTRACE_TRIPLES "/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;787;add_test;/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;0;")
add_test("moderngekko.runtime" "/home/linux/HPCOS-GC-RECOMP/ModernGekko/build-llvm20/moderngekko_runtime_test")
set_tests_properties("moderngekko.runtime" PROPERTIES  _BACKTRACE_TRIPLES "/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;812;add_test;/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;0;")
add_test("moderngekko.dol_loader" "/home/linux/HPCOS-GC-RECOMP/ModernGekko/build-llvm20/moderngekko_dol_loader_test")
set_tests_properties("moderngekko.dol_loader" PROPERTIES  _BACKTRACE_TRIPLES "/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;821;add_test;/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;0;")
add_test("moderngekko.boot_environment" "/home/linux/HPCOS-GC-RECOMP/ModernGekko/build-llvm20/moderngekko_boot_environment_test")
set_tests_properties("moderngekko.boot_environment" PROPERTIES  _BACKTRACE_TRIPLES "/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;830;add_test;/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;0;")
add_test("moderngekko.gekko_definitions" "/home/linux/HPCOS-GC-RECOMP/ModernGekko/build-llvm20/moderngekko_gekko_definitions_test")
set_tests_properties("moderngekko.gekko_definitions" PROPERTIES  _BACKTRACE_TRIPLES "/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;842;add_test;/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;0;")
add_test("moderngekko.interpreter" "/home/linux/HPCOS-GC-RECOMP/ModernGekko/build-llvm20/moderngekko_interpreter_test")
set_tests_properties("moderngekko.interpreter" PROPERTIES  _BACKTRACE_TRIPLES "/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;851;add_test;/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;0;")
add_test("moderngekko.hardware_core" "/home/linux/HPCOS-GC-RECOMP/ModernGekko/build-llvm20/moderngekko_hardware_core_test")
set_tests_properties("moderngekko.hardware_core" PROPERTIES  _BACKTRACE_TRIPLES "/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;860;add_test;/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;0;")
add_test("moderngekko.io_services" "/home/linux/HPCOS-GC-RECOMP/ModernGekko/build-llvm20/moderngekko_io_services_test")
set_tests_properties("moderngekko.io_services" PROPERTIES  _BACKTRACE_TRIPLES "/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;869;add_test;/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;0;")
add_test("moderngekko.audio_system" "/home/linux/HPCOS-GC-RECOMP/ModernGekko/build-llvm20/moderngekko_audio_system_test")
set_tests_properties("moderngekko.audio_system" PROPERTIES  _BACKTRACE_TRIPLES "/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;878;add_test;/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;0;")
add_test("moderngekko.gx_commands" "/home/linux/HPCOS-GC-RECOMP/ModernGekko/build-llvm20/moderngekko_gx_commands_test")
set_tests_properties("moderngekko.gx_commands" PROPERTIES  _BACKTRACE_TRIPLES "/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;887;add_test;/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;0;")
add_test("moderngekko.gx_state" "/home/linux/HPCOS-GC-RECOMP/ModernGekko/build-llvm20/moderngekko_gx_state_test")
set_tests_properties("moderngekko.gx_state" PROPERTIES  _BACKTRACE_TRIPLES "/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;896;add_test;/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;0;")
add_test("moderngekko.gx_vertex" "/home/linux/HPCOS-GC-RECOMP/ModernGekko/build-llvm20/moderngekko_gx_vertex_test")
set_tests_properties("moderngekko.gx_vertex" PROPERTIES  _BACKTRACE_TRIPLES "/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;905;add_test;/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;0;")
add_test("moderngekko.gx_conformance" "/home/linux/HPCOS-GC-RECOMP/ModernGekko/build-llvm20/moderngekko_gx_conformance_test")
set_tests_properties("moderngekko.gx_conformance" PROPERTIES  _BACKTRACE_TRIPLES "/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;914;add_test;/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;0;")
add_test("moderngekko.gx_texture" "/home/linux/HPCOS-GC-RECOMP/ModernGekko/build-llvm20/moderngekko_gx_texture_test")
set_tests_properties("moderngekko.gx_texture" PROPERTIES  _BACKTRACE_TRIPLES "/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;923;add_test;/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;0;")
add_test("moderngekko.gx_pipeline" "/home/linux/HPCOS-GC-RECOMP/ModernGekko/build-llvm20/moderngekko_gx_pipeline_test")
set_tests_properties("moderngekko.gx_pipeline" PROPERTIES  _BACKTRACE_TRIPLES "/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;932;add_test;/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;0;")
add_test("moderngekko.dolphin_shader" "/home/linux/HPCOS-GC-RECOMP/ModernGekko/build-llvm20/moderngekko_dolphin_shader_test")
set_tests_properties("moderngekko.dolphin_shader" PROPERTIES  _BACKTRACE_TRIPLES "/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;941;add_test;/home/linux/HPCOS-GC-RECOMP/ModernGekko/CMakeLists.txt;0;")
subdirs("vendor/dolphin")
subdirs("vendor/dolphin/DolRecomp")
